//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empire_BSA_Import
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPACO_ACOInsights_DataExtraction_Providers
    {
        public Nullable<int> UniqueKey { get; set; }
        public string Eligibility { get; set; }
        public string Practice { get; set; }
        public string TIN { get; set; }
        public string Provider { get; set; }
        public string NPI { get; set; }
        public string MemberSource { get; set; }
        public string Covid19Rule { get; set; }
        public string Year { get; set; }
        public string Category { get; set; }
        public string Metric { get; set; }
        public string QTR1 { get; set; }
        public string QTR2 { get; set; }
        public string QTR3 { get; set; }
        public string QTR4 { get; set; }
        public string AVG { get; set; }
        public string WeightedAvg { get; set; }
        public string YTD { get; set; }
        public string Membership { get; set; }
        public string DATASET { get; set; }
        public int Rec_ID { get; set; }
        public string SAHS { get; set; }
    }
}
